Laptop_Ecommerce/Areas/Admin/Controllers/LaptopController.cs
using Laptop_Ecommerce.DataAccess.Rpository.IRepository;
using Laptop_Ecommerce.Models;
using Laptop_Ecommerce.Models.ViewModels;
using Laptop_Ecommerce.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Laptop_Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class LaptopController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public LaptopController(IUnitOfWork unitOfWork,IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            LaptopVM laptopVM = new LaptopVM()
            {
                laptop = new Laptop(),
                LaptopCompanyList = _unitOfWork.LaptopCompany.GetAll().Select(lcl => new SelectListItem
                {
                    Text = lcl.Name,
                    Value = lcl.Id.ToString()
                }),
                ProcessorList = _unitOfWork.Processor.GetAll().Select(pl => new SelectListItem
                {
                    Text = pl.Name,
                    Value = pl.Id.ToString()
                }),
                GraphicsCardList = _unitOfWork.GraphicsCard.GetAll().Select(gcl => new SelectListItem
                {
                    Text = gcl.Name,
                    Value = gcl.Id.ToString()
                })
            };
            if (id == null) return View(laptopVM);
            laptopVM.laptop = _unitOfWork.Laptop.Get(id.GetValueOrDefault());
            if (laptopVM.laptop == null) return BadRequest();
            return View(laptopVM);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Upsert(LaptopVM laptopVM)
        {
            if(!ModelState.IsValid)
            {
                var webRootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if(files.Count()>0)
                {
                    var fileName = Guid.NewGuid().ToString();
                    var extension = Path.GetExtension(files[0].FileName);
                    var uploads = Path.Combine(webRootPath, @"images\laptops");
                    if(laptopVM.laptop.Id!=0)
                    {
                        var imageExists = _unitOfWork.Laptop.Get(laptopVM.laptop.Id).ImageUrl;
                        laptopVM.laptop.ImageUrl = imageExists;
                    }
                    if(laptopVM.laptop.ImageUrl!=null)
                    {
                        var imagePath = Path.Combine(webRootPath, laptopVM.laptop.ImageUrl.Trim('\\'));
                        if(System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                    using(var fileStream=new FileStream(Path.Combine(uploads,fileName+extension),FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    laptopVM.laptop.ImageUrl=@"\images\laptops\"+fileName+extension;
                }
                else
                {
                    if(laptopVM.laptop.Id!=0)
                    {
                        var imageExists = _unitOfWork.Laptop.Get(laptopVM.laptop.Id).ImageUrl;
                        laptopVM.laptop.ImageUrl = imageExists;
                    }
                }
                if (laptopVM.laptop.Id == 0)
                    _unitOfWork.Laptop.Add(laptopVM.laptop);
                else
                    _unitOfWork.Laptop.Update(laptopVM.laptop);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            else
            {
                 laptopVM = new LaptopVM()
                {
                    laptop = new Laptop(),
                    LaptopCompanyList = _unitOfWork.LaptopCompany.GetAll().Select(lcl => new SelectListItem
                    {
                        Text = lcl.Name,
                        Value = lcl.Id.ToString()
                    }),
                    ProcessorList = _unitOfWork.Processor.GetAll().Select(pl => new SelectListItem
                    {
                        Text = pl.Name,
                        Value = pl.Id.ToString()
                    }),
                    GraphicsCardList = _unitOfWork.GraphicsCard.GetAll().Select(gcl => new SelectListItem
                    {
                        Text = gcl.Name,
                        Value = gcl.Id.ToString()
                    })
                };
                if(laptopVM.laptop.Id!=0)
                {
                    laptopVM.laptop = _unitOfWork.Laptop.Get(laptopVM.laptop.Id);
                }
                return View(laptopVM);
            }
        }
        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.Laptop.GetAll(includePropties: "LaptopCompany,Processor,GraphicsCard") });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var laptopInDb = _unitOfWork.Laptop.Get(id);
            if (laptopInDb == null)
                return Json(new { success = false, message = "Something Went Wrong While Deleting Data!!!" });
            var webRootPath = _webHostEnvironment.WebRootPath;
            var imagePath = Path.Combine(webRootPath, laptopInDb.ImageUrl.Trim('\\'));
            if(System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }
            _unitOfWork.Laptop.Remove(laptopInDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Data Deleted Successfully!!!" });
        }
        #endregion
    }
}

Laptop_Ecommerce/Areas/Admin/Controllers/OrdersController.cs
using Laptop_Ecommerce.DataAccess.Data;
using Laptop_Ecommerce.DataAccess.Rpository.IRepository;
using Laptop_Ecommerce.Models;
using Laptop_Ecommerce.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using System.Security.Claims;
using System.Text;

namespace Laptop_Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class OrdersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailSender _emailSender;

        public OrdersController(IUnitOfWork unitOfWork,ApplicationDbContext context,IEmailSender emailSender, UserManager<IdentityUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _context = context;
            _userManager = userManager;
            _emailSender = emailSender;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ByDateTime(DateTime? datetime1, DateTime? datetime2)
        {
            if(datetime1==null&&datetime2==null)
            {
                return RedirectToAction("Index");
            }
            if (datetime2 == null)
            {
                var date = _unitOfWork.OrderHeader.GetAll(u => u.OrderDate.Date == datetime1);
                return View(date);
            }
            if (datetime1 == null)
            {
                var date = _unitOfWork.OrderHeader.GetAll(u => u.OrderDate.Date == datetime2);
                return View(date);
            }
            IQueryable<OrderHeader> query = from o in _context.OrderHeaders select o;
            if(datetime1!=null&&datetime2!=null)
            {
                query = from o in _context.OrderHeaders where o.OrderDate.Date > datetime1 && o.OrderDate.Date <= datetime2 select o;
            }
            return View(query);
        }
        public IActionResult Details(int id)
        {
            var allDetails = _unitOfWork.OrderDetails.FirstOrDefault(u => u.OrderHeaderId == id, includePropties:"Laptop,OrderHeader,Laptop.LaptopCompany,Laptop.Processor,Laptop.GraphicsCard,OrderHeader.ApplicationUser");
            return View(allDetails);
        }
        public IActionResult StatusApproved()
        {
            var approved = _unitOfWork.OrderHeader.GetAll().Where(os => os.OrderStatus == "Approved");
            if(approved.ToList().Count==0)
            {
                return View("_NoRecord");
            }
            return View(approved);
        }
        public IActionResult StatusPending()
        {
            var approved = _unitOfWork.OrderHeader.GetAll().Where(os => os.OrderStatus == "Pending");
            if (approved.ToList().Count == 0)
            {
                return View("_NoRecord");
            }
            return View(approved);
        }
        public async Task<IActionResult> CancelOrder(int id)
        {
            var cancel = _unitOfWork.OrderHeader.Get(id);
            cancel.OrderStatus = "Cancelled";
            //
            //var claimsIdentity = (ClaimsIdentity)User.Identity;
            //var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            //session
            //if (claim != null)
            //{
            //    var count = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == claim.Value).ToList().Count;
            //    HttpContext.Session.SetInt32(SD.Ss_CartSessionCount, count);
            //}

            var user = _unitOfWork.ApplicationUser.FirstOrDefault(u => u.Id == cancel.ApplicationUserId);

            var userId = await _userManager.GetUserIdAsync(user);
            var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            await _emailSender.SendEmailAsync(user.Email, $"Your Order's Has Been Cancelled for Order Id:{cancel.Id}",
                "Please Contact Us For More Information!!!");
            //
            _unitOfWork.OrderHeader.Update(cancel);
            _unitOfWork.Save();
            return View("Index");
        }
        public IActionResult StatusCancelled()
        {
            var approved = _unitOfWork.OrderHeader.GetAll().Where(os => os.OrderStatus == "Cancelled");
            if (approved.ToList().Count == 0)
            {
                return View("_NoRecord");
            }
            return View(approved);
        }
        public IActionResult StatusRefunded()
        {
            var approved = _unitOfWork.OrderHeader.GetAll().Where(os => os.OrderStatus == "Refunded");
            if (approved.ToList().Count == 0)
            {
                return View("_NoRecord");
            }
            return View(approved);
        }
        public IActionResult StatusProcessing()
        {
            var approved = _unitOfWork.OrderHeader.GetAll().Where(os => os.OrderStatus == "Processing");
            if (approved.ToList().Count == 0)
            {
                return View("_NoRecord");
            }
            return View(approved);
        }
        public IActionResult StatusShipped()
        {
            var approved = _unitOfWork.OrderHeader.GetAll().Where(os => os.OrderStatus == "Shipped");
            if (approved.ToList().Count == 0)
            {
                return View("_NoRecord");
            }
            return View(approved);
        }
     
        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.OrderHeader.GetAll() });
        }
        //[HttpGet]
        //public IActionResult GetAll()
        //{
        //    return Json(new { data = _unitOfWork.OrderHeader.GetAll() });
        //}
        //[HttpGet]
        //public IActionResult StatusApproved()
        //{
        //    var approved = _unitOfWork.OrderHeader.GetAll().Where(os => os.OrderStatus == "Approved");
        //    return View(approved);
        //}
        //[HttpGet]

        //public IActionResult StatusPending()
        //{
        //    var approved = _unitOfWork.OrderHeader.GetAll().Where(os => os.OrderStatus == "Pending");
        //    return View(approved);
        //}
        //[HttpGet]

        //public IActionResult StatusCancelled()
        //{
        //    var approved = _unitOfWork.OrderHeader.GetAll().Where(os => os.OrderStatus == "Cancelled");
        //    return View(approved);
        //}
        //[HttpGet]

        //public IActionResult StatusRefunded()
        //{
        //    var approved = _unitOfWork.OrderHeader.GetAll().Where(os => os.OrderStatus == "Refunded");
        //    return View(approved);
        //}
        //[HttpGet]

        //public IActionResult StatusProcessing()
        //{
        //    var approved = _unitOfWork.OrderHeader.GetAll().Where(os => os.OrderStatus == "Processing");
        //    return View(approved);
        //}
        //[HttpGet]

        //public IActionResult StatusShipped()
        //{
        //    var approved = _unitOfWork.OrderHeader.GetAll().Where(os => os.OrderStatus == "Shipped");
        //    return View(approved);
        //}
        //[HttpGet]
        //public IActionResult AllDetails()
        //{
        //    var allDetails = _unitOfWork.OrderDetails.GetAll();
        //    return Json(new { data = allDetails });
        //}
        #endregion
    }
}

Laptop_Ecommerce/Areas/Admin/Controllers/UserController.cs
using Laptop_Ecommerce.DataAccess.Data;
using Laptop_Ecommerce.DataAccess.Rpository.IRepository;
using Laptop_Ecommerce.Models;
using Laptop_Ecommerce.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Laptop_Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IUnitOfWork _unitOfWork;
        public UserController(IUnitOfWork unitOfWork, ApplicationDbContext context)
        {
            _context = context;
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            var userList = _context.ApplicationUsers.ToList();
            var roles = _context.Roles.ToList ();
            var userRole = _context.UserRoles.ToList();
            foreach (var user in userList)
            {
                var roleId = userRole.FirstOrDefault(rl => rl.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(r => r.Id == roleId).Name;
                if(user.CompanyId!=null)
                {
                    user.Company = new Company()
                    {
                        Name = _unitOfWork.Company.Get(Convert.ToInt32(user.CompanyId)).Name
                    };
                }
                if (user.Company == null)
                {
                    user.Company = new Company()
                    {
                        Name = ""
                    };
                }
            }
            var adminUser = userList.FirstOrDefault(au => au.Role == SD.Role_Admin);
            userList.Remove(adminUser);
            return Json(new { data = userList });
        }
        [HttpPost]
        public IActionResult LockUnlock([FromBody]string id)
        {
            bool isLocked = false;
            var userInDb = _context.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if (userInDb == null)
                return Json(new { success = false, message = "Something Went Wrong While Locking/Unlocking The User!!!" });
            if(userInDb!=null&&userInDb.LockoutEnd>DateTime.Now)
            {
                userInDb.LockoutEnd = DateTime.Now;
                isLocked = false;
            }
            else
            {
                userInDb.LockoutEnd = DateTime.Now.AddYears(100);
                isLocked=true;
            }
            _context.SaveChanges();
            return Json(new { success = true, message = isLocked == true ? "User Locked Successfully" : "User Unlocked Successfully" });
        }
        #endregion
    }
}

Laptop_Ecommerce/Views/Shared/_Layout.cshtml
@using Laptop_Ecommerce.Utility;
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laptop_Ecommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrapLumen.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Laptop_Ecommerce.styles.css" asp-append-version="true" />

    @*CSS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   LINKS*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

    <link rel="icon"type="image/x-icon"href="~/favicon.ico"/>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">
                    @* Buy Laptops
                    <i class="fas fa-laptop-code"></i>*@
                    <img src="~/browsing.png" height="35" width="35" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fas fa-home"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-brend dropdown">
                                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content-Management</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="LaptopCompany" asp-action="Index">Laptop Companies</a>
                                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Processor" asp-action="Index">Processors</a>
                                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="GraphicsCard" asp-action="Index">GraphicsCards</a>
                                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Laptop" asp-action="Index">Laptops</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Admin) || (User.IsInRole(SD.Role_Employee)))
                        {
                            <li class="nav-brend dropdown">
                                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Companies / Users</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Company" asp-action="Index">Companies</a>
                                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-brend dropdown">
                                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Order-Management</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="Index">All Orders</a>
                                </div>
                            </li>
                        }
                        @*User Orders*@
                         @if (User.IsInRole(SD.Role_Individual))
                        {
                            <li class="nav-brend dropdown">
                                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Orders History</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item text-center" asp-area="Customer" asp-controller="UserOrder" asp-action="Index">Previous Orders</a>
                                </div>
                            </li>
                        }

                        @if (httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_CartSessionCount) != null && httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_CartSessionCount) != 0)
                        {
                            var count = httpContextAccessor.HttpContext.Session.GetInt32(SD.Ss_CartSessionCount);
                            <li>
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link text-white">
                                    <i class="fas fa-shopping-cart"></i>&nbsp;(@count)
                                </a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a class="nav-link text-white">
                                    <i class="fas fa-shopping-cart"></i>&nbsp;(0)
                                </a>
                            </li>
                        }
                    </ul>
                    @using (Html.BeginForm("Index", "Home", FormMethod.Get))
                    {
                        <b class="text-white">Search by</b>
                        @Html.RadioButton("searchBy","company",true)
                        <span class="text-white">Brand</span>
                        @Html.RadioButton("searchBy","modelName",true)
                        <span class="text-white">Model Name</span>
                        @Html.TextBox("search")
                        <input type="submit" value="search" />
                    }


                    @* <form asp-controller="Home" asp-action="Index" method="get" class="d-flex">
                    <input class="form-control me-sm-2" type="text" name="SearchString" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
                    @*<form asp-controller="Home" asp-action="Index" method="get">
                    <p>
                    Title: <input type="text" name="SearchString" />
                    <input type="submit" value="Filter" />
                    </p>
                    </form>*@
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container text-white">
            &copy; 2023 - Laptop_Ecommerce - <a class="text-info" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*JS LINKS*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>

    @*Slider*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Laptop_Ecommerce/Views/Shared/_NoRecord.cshtml
<div class="container row">
    <div class="col-12 text-center">
        <div class="offset-11">
            <div class="nav-brend dropdown">
                <a class="nav-link dropdown-toggle text-success" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Orders By Status</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="Index">All Orders</a>
                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="StatusApproved">Approved Orders</a>
                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="StatusPending">Pending Orders</a>
                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="StatusCancelled">Cancelled Orders</a>
                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="StatusRefunded">Refunded Orders</a>
                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="StatusProcessing">InProcess Orders</a>
                    <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="StatusShipped">Shipped Orders</a>
                </div>
            </div>
        </div>
        <img src="~/images/noRecord.jpg" width="50%" />
    </div>
    <div class="col-12 text-center" style="color:red">
        <br />
        <h2>No Matching Result Found!!!</h2> <br />
       <a asp-action="Index" class="btn btn-primary">Continue Managing</a>
        <br />
    </div>
</div>  

Laptop_Ecommerce/Views/Shared/_SaveUpdateBackToListButtons.cshtml
<div class="row">
    <div class="col">
        @if (Model.Id == 0)
        {
            <button type="submit" class="btn btn-success form-control">
                <i class="fas fa-save"></i> Save
            </button>
        }
        else
        {
            <button type="submit" class="btn btn-success form-control">
                <i class="fas fa-save"></i> Update
            </button>
        }
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-info form-control">
            <i class="fas fa-list"></i>Back To List
        </a>
    </div>
</div>

Laptop_Ecommerce/Views/Shared/_ShowingOrdersByStatus.cshtml
@model IEnumerable<Laptop_Ecommerce.Models.OrderHeader>

<div class="col-1">
    <div class="nav-brend dropdown">
        <a class="nav-link dropdown-toggle text-success" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Orders By Status</a>
        <div class="dropdown-menu">
            <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="Index">All Orders</a>
            <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="StatusApproved">Approved Orders</a>
            <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="StatusPending">Pending Orders</a>
            <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="StatusCancelled">Cancelled Orders</a>
            <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="StatusRefunded">Refunded Orders</a>
            <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="StatusProcessing">InProcess Orders</a>
            <a class="dropdown-item text-center" asp-area="Admin" asp-controller="Orders" asp-action="StatusShipped">Shipped Orders</a>
        </div>
    </div>
</div>
<div class="border container p-2 m-2">
    <table class="table table-striped table-bordered table-hover table-responsive active">
        <thead>
            <tr>
                <th class="text-center text-primary">Customer Name</th>
                <th class="text-center text-primary">Payment Status</th>
                <th class="text-center text-primary">Total Amount</th>
                <th class="text-center text-primary">Order Status</th>
                <th class="text-center text-primary">Date & Time</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center ">@item.Name</td>
                    <td class="text-center ">@item.PaymentStatus</td>
                    <td class="text-center ">@item.OrderTotal</td>
                    <td class="text-center ">@item.OrderStatus</td>
                    <td class="text-center ">@item.OrderDate</td>
                </tr>
            }
        </tbody>
    </table>
</div>